# Generated by Django 5.1.3 on 2024-12-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoavatar', '0003_desafio_recompensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('recompensa', models.ManyToManyField(blank=True, related_name='personajes', to='ecoavatar.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='ecoavatar.user')),
            ],
        ),
    ]
